# Setup
#title:               Diego Derman
#tagline:             'Github page'
#description:         'This would be the description.'
#url:                 http://diegoderman.github.io
#baseurl:             ''
#paginate:            5
#permalink:           pretty

# About/contact
author:
  name:              Diego Derman
  url:               http://diegoderman.github.io
  email:             dderman@iu.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
